/**
 * A part of a session message (stub of the SDK's Part union).
 */
interface PartLike {
    /**
     * Part type, e.g. "text".
     */
    type: string;
    /**
     * Text content for text parts.
     */
    text?: string;
    /**
     * Marks parts generated by the system rather than the user.
     */
    synthetic?: boolean;
}

/**
 * Creation time of a message.
 */
interface TimeLike {
    /**
     * Epoch milliseconds.
     */
    created?: number;
}

/**
 * Message envelope fields (stub of the SDK's Message info).
 */
interface MessageInfoLike {
    /**
     * Message role.
     */
    role: 'user' | 'assistant';
    /**
     * Creation time.
     */
    time?: TimeLike;
}

/**
 * A stub of a session message as returned by opencode's SDK client.
 */
interface MessageLike {
    /**
     * Message envelope fields.
     */
    info: MessageInfoLike;
    /**
     * Message parts.
     */
    parts?: PartLike[];
}

/**
 * Extracts the text of the most recent message of the requested role.
 * Returns null when no such message has a non-synthetic text part.
 * @param messages messages from session.messages
 * @param role message role to pick
 * @returns joined text of the newest matching message, or null
 */
export function newestText(
    messages: MessageLike[],
    role: 'user' | 'assistant',
): string | null {
    const candidates = messages
        .filter((m) => m.info?.role === role)
        .sort(
            (a, b) => (a.info.time?.created ?? 0) - (b.info.time?.created ?? 0),
        );
    const latest = candidates[candidates.length - 1];
    if (!latest) {
        return null;
    }
    const texts = (latest.parts ?? [])
        .filter((p) => p.type === 'text' && !p.synthetic && p.text?.trim())
        .map((p) => p.text ?? '');
    return texts.length > 0 ? texts.join('\n') : null;
}
