/**
 * A part of a session message (stub of the SDK's Part union).
 */
interface PartLike {
    /**
     * Part type, e.g. "text".
     */
    type: string;
    /**
     * Text content for text parts.
     */
    text?: string;
    /**
     * Marks parts generated by the system rather than the user.
     */
    synthetic?: boolean;
}

/**
 * Creation time of a message.
 */
interface TimeLike {
    /**
     * Epoch milliseconds.
     */
    created?: number;
}

/**
 * Message envelope fields (stub of the SDK's Message info).
 */
interface MessageInfoLike {
    /**
     * Message role.
     */
    role: 'user' | 'assistant';
    /**
     * Creation time.
     */
    time?: TimeLike;
}

/**
 * A stub of a session message as returned by opencode's SDK client.
 */
interface MessageLike {
    /**
     * Message envelope fields.
     */
    info: MessageInfoLike;
    /**
     * Message parts.
     */
    parts?: PartLike[];
}

/**
 * Skips messages without a non-synthetic text part and returns the text of
 * the first (by direction) textual message of the requested role.
 * @param messages messages from session.messages (any order; sorted here)
 * @param role message role to pick
 * @param which pick the first ('first' — rename semantics, README promises
 * the first textful user message) or the most recent ('newest' — replies)
 * @returns joined text of the picked message, or null
 */
export function messageText(
    messages: MessageLike[],
    role: 'user' | 'assistant',
    which: 'first' | 'newest',
): string | null {
    const candidates = messages
        .filter((m) => m.info?.role === role)
        .sort(
            (a, b) => (a.info.time?.created ?? 0) - (b.info.time?.created ?? 0),
        );
    const ordered = which === 'first' ? candidates : [...candidates].reverse();
    for (const message of ordered) {
        const texts = (message.parts ?? [])
            .filter((p) => p.type === 'text' && !p.synthetic && p.text?.trim())
            .map((p) => p.text ?? '');
        if (texts.length > 0) {
            return texts.join('\n');
        }
    }
    return null;
}
